name: Salesforce CICD

on:
    pull_request:
      types: [opened, synchronize]
    push:
      branches:
        - main
    
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
                ref: "${{ github.head_ref }}"
          - name: Fetching Commits
            if: github.event_name == 'pull_request'
            run: |
                SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
                git fetch origin $SOURCE_BRANCH
                TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
                git fetch origin $TARGET_BRANCH
                echo "Pull Request : SOURCE_BRANCH-$SOURCE_BRANCH - - - TARGET_BRANCH-$TARGET_BRANCH"
                HEAD_COMMIT_ID=$(git rev-parse origin/${{ github.head_ref }})
                echo "HEAD_COMMIT_ID =$HEAD_COMMIT_ID" >> $GITHUB_ENV
                BASE_COMMIT_ID=$(git rev-parse origin/${{ github.base_ref }})
                echo "BASE_COMMIT_ID =$BASE_COMMIT_ID" >> $GITHUB_ENV
                sh scripts/shell/deltaComponentRetrieve.sh $HEAD_COMMIT_ID $BASE_COMMIT_ID
                echo " Below are package.xml Components"
                cat package/package.xml
                echo "========================================================="
                echo " Below are destructive package.xml Components"
                cat destructiveChanges/destructiveChanges.xml

          - name: Validate
            run: |
                npm install @salesforce/cli --global
                SFDX_AUTH_URL="force://PlatformCLI::5Aep861kFI7dkvKqCo2fts_thtdQYaDmQ_fcMxfhg6PR6hZ_quq36snLmoz_RaDutLw2hvS2.dlsXC7uL5SAPfd@platform-platform-70602-dev-ed.scratch.my.salesforce.com"
                echo $SFDX_AUTH_URL > auth-url.txt
                cat auth-url.txt
                sf org login sfdx-url --sfdx-url-file auth-url.txt
                sfdx force:source:deploy --manifest package/package.xml --targetusername test-4xal8coxzfh8@example.com  --checkonly
